apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-helm-canary
spec:
  selector:
    matchLabels:
      app: myapp-helm
      instance: myapp-helm-canary
  replicas: {{ .Values.canary.replicas }}
  template:
    metadata:
      labels:
        app: myapp-helm
        instance: myapp-helm-canary
    spec:
      containers:
      - name: myapp-helm-canary
        image: "{{ .Values.image }}:{{ .Values.canary.imageTag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        - containerPort: 8080
