apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-helm
  labels:
    release: myapp-helm
spec:
  selector:
    matchLabels:
      app: myapp-helm
  endpoints:
  - port: metrics