apiVersion: v1
kind: Service
metadata:
  name: myapp-helm
spec:
  selector:
    app: myapp-helm
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  type: {{ .Values.service.type }}