apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release          
        args: 
         - "load"
         - "-allow-initial-errors"  
         - "-t"       
         - "0"
         - "http://nginx-ingress-controller.ingress-nginx" # change above to your ip or name of ingress controller or hostname if configured          
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping